# Generated by Django 5.1.7 on 2025-05-21 09:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text="Format de l'export (ex: firekey, csv, json)", max_length=50)),
                ('encrypted', models.BooleanField(default=True)),
                ('credentials_exported', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Réussi'), ('error', 'Échoué')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'export",
                'verbose_name_plural': "Historiques d'exports",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportFileStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('analysis_status', models.CharField(choices=[('pending', 'En attente'), ('analyzing', "En cours d'analyse"), ('ready', 'Prêt'), ('error', 'Erreur')], default='pending', max_length=20)),
                ('total_credentials', models.IntegerField(default=0)),
                ('new_credentials', models.IntegerField(default=0)),
                ('duplicate_credentials', models.IntegerField(default=0)),
                ('conflict_credentials', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_file_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text="Source de l'import (ex: google, lastpass, csv)", max_length=50)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('credentials_imported', models.IntegerField(default=0)),
                ('credentials_skipped', models.IntegerField(default=0)),
                ('credentials_merged', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Réussi'), ('error', 'Échoué'), ('partial', 'Partiellement réussi')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'import",
                'verbose_name_plural': "Historiques d'imports",
                'ordering': ['-created_at'],
            },
        ),
    ]
