# Generated by Django 5.1.7 on 2025-04-17 22:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_credentialshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
