# Generated by Django 5.1.7 on 2025-05-27 21:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_tag_credential_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyDerivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=128)),
                ('iterations', models.IntegerField(default=100000)),
                ('algorithm', models.CharField(default='PBKDF2-SHA256', max_length=50)),
                ('search_salt', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_derivation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialE2E',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('encrypted_name', models.TextField()),
                ('encrypted_website', models.TextField(blank=True)),
                ('encrypted_email', models.TextField(blank=True)),
                ('encrypted_password', models.TextField()),
                ('encrypted_notes', models.TextField(blank=True)),
                ('encryption_version', models.CharField(default='1.0', max_length=10)),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('name_search_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('website_search_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('email_search_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_credential', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='e2e_version', to='credentials.credential')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e2e_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'name_search_hash'], name='credentials_user_id_4a40aa_idx'), models.Index(fields=['user', 'website_search_hash'], name='credentials_user_id_bf3f6a_idx'), models.Index(fields=['user', 'created_at'], name='credentials_user_id_fe6777_idx')],
            },
        ),
    ]
