"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Chargement du fichier .env
dotenv_path = os.path.join(BASE_DIR, '.env')
load_dotenv(dotenv_path)

# Configuration des médias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Créer le répertoire temporaire pour l'import/export si nécessaire
TEMP_UPLOAD_DIR = os.path.join(MEDIA_ROOT, 'tmp', 'imports')
os.makedirs(TEMP_UPLOAD_DIR, exist_ok=True)

# =============================================================================
# SÉCURITÉ - Configuration depuis les variables d'environnement
# =============================================================================

# OBLIGATOIRE : SECRET_KEY doit être définie dans .env
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    if os.getenv('ENVIRONMENT') == 'production':
        raise ValueError("SECRET_KEY doit être définie en production !")
    else:
        print("⚠️  ATTENTION : SECRET_KEY non définie, utilisation d'une clé de développement")
        SECRET_KEY = 'django-insecure-dev-key-CHANGEZ-MOI'

# Debug et environnement
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# Vérifications de sécurité pour la production
if ENVIRONMENT == 'production':
    if DEBUG:
        raise ValueError("DEBUG ne doit pas être activé en production !")
    if 'django-insecure' in SECRET_KEY:
        raise ValueError("SECRET_KEY doit être changée en production !")

# Hosts autorisés
ALLOWED_HOSTS_STR = os.getenv('ALLOWED_HOSTS', '')
if ALLOWED_HOSTS_STR:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1'] if DEBUG else []

# =============================================================================
# APPLICATIONS ET MIDDLEWARE
# =============================================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'accounts',
    'corsheaders',
    'credentials',
    'notifications',
    'security',
    'importexport',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.AuthRequiredMiddleware',
    'security.middleware.RequestLoggingMiddleware',
]

# =============================================================================
# CONFIGURATION CORS
# =============================================================================

CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() == 'true'

# Si CORS_ALLOW_ALL_ORIGINS est False, utilisez CORS_ALLOWED_ORIGINS
if not CORS_ALLOW_ALL_ORIGINS:
    CORS_ALLOWED_ORIGINS_STR = os.getenv('CORS_ALLOWED_ORIGINS', '')
    if CORS_ALLOWED_ORIGINS_STR:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(',') if origin.strip()]
    else:
        CORS_ALLOWED_ORIGINS = []

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# =============================================================================
# BASE DE DONNÉES - Configuration depuis les variables d'environnement
# =============================================================================

# Vérification des variables de base de données requises
required_db_vars = ['DB_NAME', 'DB_USER', 'DB_PASSWORD', 'DB_HOST']
missing_db_vars = [var for var in required_db_vars if not os.getenv(var)]

if missing_db_vars and ENVIRONMENT == 'production':
    raise ValueError(f"Variables de base de données manquantes en production : {missing_db_vars}")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'P-SP-DB01'),
        'USER': os.getenv('DB_USER', 'theo'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'lolmdr123'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# =============================================================================
# SÉCURITÉ DES MOTS DE PASSE
# =============================================================================

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# REST FRAMEWORK ET JWT
# =============================================================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Configuration JWT depuis les variables d'environnement
JWT_ACCESS_LIFETIME = int(os.getenv('JWT_ACCESS_TOKEN_LIFETIME', '86400'))  # 1 jour par défaut
JWT_REFRESH_LIFETIME = int(os.getenv('JWT_REFRESH_TOKEN_LIFETIME', '86400'))  # 1 jour par défaut

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(seconds=JWT_ACCESS_LIFETIME),
    'REFRESH_TOKEN_LIFETIME': timedelta(seconds=JWT_REFRESH_LIFETIME),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# =============================================================================
# CHIFFREMENT - Configuration depuis les variables d'environnement
# =============================================================================

# Clé AES pour le chiffrement général
AES_SECRET_KEY_STR = os.getenv('AES_SECRET_KEY')
if AES_SECRET_KEY_STR:
    if len(AES_SECRET_KEY_STR) == 32:
        AES_SECRET_KEY = AES_SECRET_KEY_STR.encode('utf-8')
    else:
        AES_SECRET_KEY = AES_SECRET_KEY_STR.encode('utf-8')[:32].ljust(32, b'0')
else:
    if ENVIRONMENT == 'production':
        raise ValueError("AES_SECRET_KEY doit être définie en production !")
    else:
        print("⚠️  ATTENTION : AES_SECRET_KEY non définie, utilisation d'une clé de développement")
        AES_SECRET_KEY = b'12345678901234567890123456789012'

# Clé pour le chiffrement des fichiers temporaires
TEMP_FILE_ENCRYPTION_KEY = os.getenv('TEMP_FILE_ENCRYPTION_KEY')
if not TEMP_FILE_ENCRYPTION_KEY:
    if ENVIRONMENT == 'production':
        raise ValueError("TEMP_FILE_ENCRYPTION_KEY doit être définie en production !")
    else:
        print("⚠️  ATTENTION : TEMP_FILE_ENCRYPTION_KEY non définie, utilisation d'une clé de développement")
        TEMP_FILE_ENCRYPTION_KEY = 'YmFzZTY0IGVuY29kZWQgMzIgYnl0ZXMga2V5IGZvciBkZXZlbG9wbWVudA=='

# =============================================================================
# CONFIGURATION DES UPLOADS
# =============================================================================

FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', '10485760'))  # 10MB
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', '10485760'))   # 10MB

# =============================================================================
# E2E ENCRYPTION
# =============================================================================

E2E_ENCRYPTION_ENABLED = os.getenv('E2E_ENCRYPTION_ENABLED', 'True').lower() == 'true'
E2E_MIGRATION_MODE = os.getenv('E2E_MIGRATION_MODE', 'True').lower() == 'true'
E2E_MIGRATION_TOKEN_LIFETIME = int(os.getenv('E2E_MIGRATION_TOKEN_LIFETIME', '3600'))

# =============================================================================
# CONFIGURATION CELERY (optionnel)
# =============================================================================

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')

if CELERY_BROKER_URL and CELERY_RESULT_BACKEND:
    CELERY_ACCEPT_CONTENT = ['json']
    CELERY_TASK_SERIALIZER = 'json'
    CELERY_RESULT_SERIALIZER = 'json'
    CELERY_TIMEZONE = 'UTC'

    from celery.schedules import crontab

    CELERY_BEAT_SCHEDULE = {
        'cleanup-expired-temp-files': {
            'task': 'importexport.tasks.cleanup_expired_temp_files',
            'schedule': crontab(minute=0),  # Toutes les heures
        },
        'cleanup-orphaned-temp-files': {
            'task': 'importexport.tasks.cleanup_orphaned_temp_files', 
            'schedule': crontab(hour=2, minute=30),  # Tous les jours à 2h30
        },
    }

# =============================================================================
# INTERNATIONALISATION
# =============================================================================

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# FICHIERS STATIQUES
# =============================================================================

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# CONFIGURATION DE LOGGING
# =============================================================================

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOG_LEVEL = os.getenv('LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'import_export_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'import_export.log'),
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'security.log'),
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'importexport': {
            'handlers': ['import_export_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

# =============================================================================
# SÉCURITÉ SUPPLÉMENTAIRE POUR LA PRODUCTION
# =============================================================================

if ENVIRONMENT == 'production':
    # Forcer HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Sécurité des cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Autres headers de sécurité
    X_FRAME_OPTIONS = 'DENY'
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# =============================================================================
# AFFICHAGE DES AVERTISSEMENTS DE SÉCURITÉ
# =============================================================================

if DEBUG and ENVIRONMENT == 'development':
    print("\n" + "="*60)
    print("🔧 MODE DÉVELOPPEMENT ACTIVÉ")
    print("="*60)
    if 'django-insecure' in SECRET_KEY:
        print("⚠️  Utilisation de la SECRET_KEY de développement")
    if 'test' in sys.argv or 'runserver' in sys.argv:
        print("💡 N'oubliez pas de configurer .env pour la production !")
    print("="*60 + "\n")