# Generated by Django 5.1.7 on 2025-04-16 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0002_credentialshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialStrengthCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.CharField(choices=[('weak', 'Faible'), ('medium', 'Moyen'), ('strong', 'Fort')], default='medium', max_length=10)),
                ('score', models.IntegerField(default=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('credential', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strength_cache', to='credentials.credential')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('security_score', models.IntegerField(default=0)),
                ('weak_passwords_count', models.IntegerField(default=0)),
                ('duplicate_passwords_count', models.IntegerField(default=0)),
                ('old_passwords_count', models.IntegerField(default=0)),
                ('total_credentials_count', models.IntegerField(default=0)),
                ('audit_details', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('credential_create', 'Création de credential'), ('credential_update', 'Mise à jour de credential'), ('credential_delete', 'Suppression de credential'), ('credential_view', 'Consultation de credential'), ('share_create', 'Création de partage'), ('share_access', 'Accès à un partage'), ('share_delete', 'Suppression de partage'), ('profile_update', 'Mise à jour du profil'), ('password_change', 'Changement de mot de passe'), ('security_audit', 'Audit de sécurité'), ('2fa_enable', 'Activation 2FA'), ('2fa_disable', 'Désactivation 2FA')], max_length=20)),
                ('action_detail', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='security_au_user_id_b9ec0c_idx'), models.Index(fields=['action_type'], name='security_au_action__2b6449_idx')],
            },
        ),
    ]
