# Generated by Django 5.1.7 on 2025-04-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='related_object_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
