# Generated by Django 5.1.7 on 2025-05-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_auditlogentry_related_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action_type',
            field=models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('credential_create', 'Création de credential'), ('credential_update', 'Mise à jour de credential'), ('credential_delete', 'Suppression de credential'), ('credential_view', 'Consultation de credential'), ('credential_create_e2e', 'Création de credential E2E'), ('share_create', 'Création de partage'), ('share_access', 'Accès à un partage'), ('share_delete', 'Suppression de partage'), ('profile_update', 'Mise à jour du profil'), ('password_change', 'Changement de mot de passe'), ('security_audit', 'Audit de sécurité'), ('2fa_enable', 'Activation 2FA'), ('2fa_disable', 'Désactivation 2FA')], max_length=50),
        ),
    ]
